### ISSUE TITLE
python小白请教怎么用。。

### ISSUE THREAD

**Issue by chegg007** [timxx/musicexporter#1]
是直接在终端 输入 python xme.py xxxx（id号）   myfav.txt吗

提示No module named lxml 。

虾米歌单一直导不出很苦恼。。谢谢了。。

**Comment by timxx** [comment]
你要装一下python-lxml这个。。不过我刚才试了一下，又不能用了，囧
有时间我再研究下怎么搞

**Comment by timxx** [comment]
请更新，已经可以用了～

**Comment by chegg007** [comment]
wow，谢谢！！

**Comment by chegg007** [comment]
File "xme.py", line 7, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

安装了pycurl之后提示这个 5555
